project_id = "vmddyjosfwvsdtofnrjf"

[functions.health-assistant]
verify_jwt = true

[functions.send-order-email]
verify_jwt = true

[functions.send-order-modification-email]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.validate-order]
verify_jwt = true